AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  customer-support-ai

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12
    Tracing: Active

    LoggingConfig:
      LogFormat: JSON

  Api:
    TracingEnabled: true

    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:

  TicketQueue:
    Type: AWS::SQS::Queue

    Properties:
      QueueName: customer-support-ticket-queue

  TicketsTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: customer-support-tickets

      BillingMode: PAY_PER_REQUEST

      StreamSpecification:
        StreamViewType: NEW_IMAGE

      AttributeDefinitions:
        - AttributeName: ticketId
          AttributeType: S

      KeySchema:
        - AttributeName: ticketId
          KeyType: HASH

  TicketAttachmentsBucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: csai-ticket-attachments

  TicketIngestionFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/ingestion/
      Handler: app.lambda_handler

      Environment:
        Variables:
          QUEUE_URL: !Ref TicketQueue

      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt TicketQueue.QueueName

      Events:
        CreateTicket:
          Type: Api

          Properties:
            Path: /tickets
            Method: post

  TicketProcessorFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/processor/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable

      Events:
        TicketQueueEvent:
          Type: SQS

          Properties:
            Queue: !GetAtt TicketQueue.Arn
            BatchSize: 1

  TicketRetrievalFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/retrieval/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable
          BUCKET_NAME: !Ref TicketAttachmentsBucket

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref TicketsTable

      Events:

        GetAllTickets:
          Type: Api

          Properties:
            Path: /tickets
            Method: get

        GetSingleTicket:
          Type: Api

          Properties:
            Path: /tickets/{ticketId}
            Method: get

  TicketUpdateFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/update/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable

      Events:

        UpdateTicket:
          Type: Api

          Properties:
            Path: /tickets/{ticketId}
            Method: put

  TicketDeleteFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/delete/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable

      Events:

        DeleteTicket:
          Type: Api

          Properties:
            Path: /tickets/{ticketId}
            Method: delete

  TicketUploadFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/upload/
      Handler: app.lambda_handler

      Environment:
        Variables:
          BUCKET_NAME: !Ref TicketAttachmentsBucket

      Policies:
        - S3CrudPolicy:
            BucketName: !Ref TicketAttachmentsBucket

      Events:

        UploadFile:
          Type: Api

          Properties:
            Path: /upload
            Method: post

  AIEnrichmentFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/ai-enrichment/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable
          KNOWLEDGE_BASE_ID: NLZB3O1MVW
          BUCKET_NAME: !Ref TicketAttachmentsBucket
          APPROVAL_TOPIC_ARN: !Ref ApprovalTopic
          AGENT_ID: 6HKX4ICTFZ
          AGENT_ALIAS_ID: O62VCMZT3H
          SUPPORT_TOOLS_FUNCTION_NAME: !Ref SupportToolsFunction

      Events:
        TicketStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt TicketsTable.StreamArn
            StartingPosition: LATEST
            BatchSize: 1

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable

        - S3ReadPolicy:
            BucketName: !Ref TicketAttachmentsBucket

        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeAgent
                - bedrock:Retrieve
                - bedrock:InvokeModel
              Resource: "*"

            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt SupportToolsFunction.Arn

            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ApprovalTopic

  KnowledgeBaseTable:
    Type: AWS::DynamoDB::Table

    Properties:
      TableName: customer-support-knowledge-base

      BillingMode: PAY_PER_REQUEST

      AttributeDefinitions:
        - AttributeName: documentId
          AttributeType: S

      KeySchema:
        - AttributeName: documentId
          KeyType: HASH

  KnowledgeBaseBucket:
    Type: AWS::S3::Bucket

    Properties:
      BucketName: csai-knowledge-base

  SupportToolsFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/tools/support-tools/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable
          APPROVAL_TOPIC_ARN: !Ref ApprovalTopic
          API_URL: "https://by26l3ewyb.execute-api.us-east-1.amazonaws.com/Prod"
    
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable
      
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref ApprovalTopic

  ApprovalTopic:
    Type: AWS::SNS::Topic

    Properties:
      TopicName: customer-support-approval-topic

  ApprovalFunction:
    Type: AWS::Serverless::Function

    Properties:
      CodeUri: backend/approval/
      Handler: app.lambda_handler

      Environment:
        Variables:
          TABLE_NAME: !Ref TicketsTable

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TicketsTable

      Events:

        ApproveRequest:
          Type: Api

          Properties:
            Path: /approve
            Method: get

        RejectRequest:
          Type: Api

          Properties:
            Path: /reject
            Method: get


  PostConfirmationFunction:
    Type: AWS::Serverless::Function

    Properties:

      FunctionName: customer-support-ai-post-confirmation

      CodeUri: backend/post-confirmation/
      Handler: app.lambda_handler

      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminAddUserToGroup
              Resource: arn:aws:cognito-idp:us-east-1:235951409983:userpool/us-east-1_SC2CeNSNP

Outputs:

  TicketApi:
    Description: API Gateway endpoint URL

    Value: !Sub >
      https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod

  TicketQueueUrl:
    Description: SQS Queue URL

    Value: !Ref TicketQueue

  TicketIngestionFunctionArn:
    Description: Ticket Ingestion Lambda ARN

    Value: !GetAtt TicketIngestionFunction.Arn

  TicketAttachmentsBucketName:
    Description: S3 Bucket Name

    Value: !Ref TicketAttachmentsBucket

  KnowledgeBaseBucketName:
    Description: Knowledge Base S3 Bucket

    Value: !Ref KnowledgeBaseBucket

  KnowledgeBaseTableName:
    Description: Knowledge Base DynamoDB Table

    Value: !Ref KnowledgeBaseTable